### PR TITLE
update to latest coffeescript

### PR DESCRIPTION
**Pull request by jakesjews**
This adds support for es2015 module syntax http://coffeescript.org/#modules

### CODE REVIEW

**Comment by jakesjews** [comment]
I changed coffeescript to use a ^ instead of a ~ to reduce the need for PRs updating the coffeescript version.

**Comment by joliss** [comment]
That's great!

I'd prefer `~` though -- I don't think CoffeeScript follows semver.

**Comment by jakesjews** [comment]
No problem I switched it back to ~

**Comment by joliss** [comment]
Thanks! Released in v0.7.0.

**Pull request merged**
