### PR TITLE
coffeescript 2.0

### LINKED ISSUE #21: Update to support CoffeeScript 2
CoffeeScript 2.0.0 was just released.

### PR DESCRIPTION
**Pull request by jakesjews**
Upgrade to coffeescript 2.0. Resolves #21. I updated travis to run node 6, 7 and 8 since coffeescript 2.0 only supports node 6+ http://coffeescript.org/#compatibility

### CODE REVIEW

**Comment by jakesjews** [comment]
@joliss is there anything else you need me to do to move this PR forward?

**Comment by boris-petrov** [comment]
Perhaps use `^` for CoffeeScript's version instead of `~`? They follow semantic versioning so it should be fine.

**Comment by jakesjews** [comment]
@boris-petrov I tried to change it to `^` in a [previous PR](https://github.com/joliss/broccoli-coffee/pull/17) but was told to change it to `~`

**Comment by boris-petrov** [comment]
@jakesjews - hm, I'm trying to find where exactly I read that CoffeeScript since version 2 will follow semantic versioning. The [changelog](http://coffeescript.org/#changelog) seems to somewhat agree with me. I'm not 100% sure though. But in any case I would prefer a `^` as I can't depend on `broccoli-coffee` keeping up with the rapid development of CoffeeScript and release a new version whenever the other guys do. And I do want to use the latest features they implement. Just my two cents. :)

**Comment by jakesjews** [comment]
@boris-petrov I totally agree with you just mentioning why I haven't changed it 👍

**Comment by joliss** [comment]
Thanks, and sorry for the long delay! I just squashed your commits into a91531f with minor changes, and released broccoli-coffee 1.0.0.

**Comment by jakesjews** [comment]
@joliss awesome thanks a bunch!

**Pull request closed without merging**
